
### Filtering Algorithms Implementation and Evaluation

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

from src import data_loader, utils
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ratings, movies, users, genres, occupation = data_loader.load_data()

movie_data_array = ratings[['userId', 'movieId', 'rating']].values
print(movie_data_array)
cosine_similarity, pearson_correlation = utils.user_based_cf(1,movie_data_array)
print(cosine_similarity)
print(pearson_correlation)



[[ 196  242    3]
 [ 186  302    3]
 [  22  377    1]
 ...
 [ 276 1090    1]
 [  13  225    2]
 [  12  203    3]]
[]
[]
